name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia por tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -t ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Si no existe la carpeta, clonamos el repo con sudo (por /var/www)
            if [ ! -d /var/www/Steam-News-Hub ]; then
              sudo git clone https://github.com/tu-usuario/tu-repo.git /var/www/Steam-News-Hub
              sudo chown -R $USER:$USER /var/www/Steam-News-Hub
            else
              cd /var/www/Steam-News-Hub
              sudo git pull origin main
            fi

            # Entramos al directorio
            cd /var/www/Steam-News-Hub

            # Bajamos y levantamos los contenedores docker
            sudo docker-compose down || true
            sudo docker-compose up -d --build
          EOF
